-- MySQL Script generated by MySQL Workbench
-- Wed Jun 21 16:34:58 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema desafio_cotacao
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema desafio_cotacao
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `desafio_cotacao` DEFAULT CHARACTER SET utf8 ;
USE `desafio_cotacao` ;

-- -----------------------------------------------------
-- Table `desafio_cotacao`.`tb_parceiros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `desafio_cotacao`.`tb_parceiros` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `cnpj` VARCHAR(14) NOT NULL,
  `endereco` VARCHAR(100) NULL,
  `uf_cobertura` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `desafio_cotacao`.`tb_viabilidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `desafio_cotacao`.`tb_viabilidades` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `logradouro` VARCHAR(100) NULL,
  `numero` VARCHAR(20) NULL,
  `bairro` VARCHAR(100) NULL,
  `cidade` VARCHAR(100) NULL,
  `uf` VARCHAR(2) NULL,
  `produto` VARCHAR(45) NULL,
  `velocidade` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `desafio_cotacao`.`tb_resultados_viabilidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `desafio_cotacao`.`tb_resultados_viabilidades` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `resultado` VARCHAR(45) NOT NULL,
  `id_viabilidade` INT NOT NULL,
  `id_parceiro` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_resultado_viabilidade_tb_viabilidade_idx` (`id_viabilidade` ASC),
  INDEX `fk_tb_resultado_viabilidade_tb_parceiro1_idx` (`id_parceiro` ASC),
  CONSTRAINT `fk_tb_resultado_viabilidade_tb_viabilidade`
    FOREIGN KEY (`id_viabilidade`)
    REFERENCES `desafio_cotacao`.`tb_viabilidades` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_resultado_viabilidade_tb_parceiro1`
    FOREIGN KEY (`id_parceiro`)
    REFERENCES `desafio_cotacao`.`tb_parceiros` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
